apiVersion: batch/v1
kind: CronJob
metadata:
  name: pi-calculation-cronjob
spec:
  # Schedule: Run every minute.
  # This is great for quickly generating history for a POC.
  # In a real scenario, this might be "0 * * * *" (every hour).
  schedule: "*/1 * * * *"

  # This part is your original Job spec, nested under 'jobTemplate'
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pi-job
        spec:
          containers:
          - name: pi
            image: perl:5.34.0
            command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(20000)"]
            resources:
              requests:
                cpu: "50m"
                memory: "100Mi"
              limits:
                cpu: "1000m"
                memory: "200Mi"
          restartPolicy: Never
      backoffLimit: 4

  # Optional: Keep only the last 3 successful and 1 failed job history
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1