datadog:
  site: datadoghq.com                  # use datadoghq.eu if you're in the EU
  apiKeyExistingSecret: datadog-secret
  clusterName: my-cluster          # change this to your actual EKS cluster name

  logs:
    enabled: true                      # enable log collection
  apm:
    enabled: true                      # enable trace collection (APM)
  processAgent:
    enabled: true                      # monitor process-level activity
  kubeStateMetricsEnabled: true        # enable kube-state-metrics integration
  leaderElection: true                 # required for cluster-level data collection
  orchestratorExplorer:
    enabled: true

  tags:
    - env:dev
    - team:infra
    - cluster:my-cluster

agents:
  containerLogs:
    enabled: true

clusterAgent:
  enabled: true
  metricsProvider:
    enabled: true                      # needed for HPA/VPA using external metrics
