datadog:
  # General Settings
  site: datadoghq.com
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  clusterName: my-cluster # change this to your actual EKS cluster name

  # Global Tags
  tags:
    - "env:dev"
    - "team:infra"
    - "cluster:my-cluster"

  # Enable Core Features
  logs:
    enabled: true
  apm:
    instrumentation:
      enabled: true # Correct way to enable APM/tracing
  processAgent:
    enabled: true
  orchestratorExplorer:
    enabled: true

  # --- Recommended VPA and KSM Configuration ---
  # Use the kubeStateMetricsCore block for modern KSM configuration
  kubeStateMetricsCore:
    enabled: true
    # This is the correct and recommended way to collect VPA metrics
    collectVpaMetrics: true

  # --- Cluster Agent Configuration ---
  clusterAgent:
    enabled: true
    # Required for HPA to use Datadog metrics and for collecting cluster-level metrics
    leaderElection: true
    metricsProvider:
      enabled: true # Keep this if you use Datadog metrics for HPA

agents:
  containerLogs:
    enabled: true