---
# =========================================================================
# Workload 1: Stateless Web Server (Over-provisioned)
#
# Type: Deployment
# Goal: To see VPA recommend a significant reduction in resources.
# This is a classic "low-hanging fruit" for VPA.
# We are intentionally requesting 1 CPU and 1 GiB of memory, which is
# far more than an idle Nginx server needs.
# =========================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateless-nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.3-alpine # Using a specific, recent version
        ports:
        - containerPort: 80
        # --- VPA TARGET ---
        # These requests are intentionally set very high. VPA should recommend
        # much lower values after observing the pod's actual usage.
        resources:
          requests:
            cpu: "1000m"  # 1 CPU
            memory: "1Gi" # 1 GiB
          limits:
            cpu: "1000m"
            memory: "1Gi"