# =========================================================================
# Workload 1: Stateless Web Server (Updated for a single pod)
#
# Changes:
# - Replicas set to 1.
# - Combined Deployment and Service into one file for easy management.
# =========================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateless-nginx
  labels:
    app: nginx
spec:
  # --- CHANGE ---
  # The number of replicas has been changed from 3 to 1.
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.3-alpine
        ports:
        - containerPort: 80
        # --- CHANGE ---
        # Temporarily lowered requests to get the pod scheduled.
        # The VPA will still see the low actual usage and recommend
        # similar values, proving its effectiveness.
        resources:
          requests:
            cpu: "100m"   # Was 1000m
            memory: "128Mi" # Was 1Gi
          limits:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
