apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# kubectl apply -f nginx-service.yaml

# To get the "EXTERNAL-IP" or "HOSTNAME"
# kubectl get service nginx-load-balancer

# The test URL will be http://a1b2c3d4e5.us-east-1.elb.amazonaws.com