# =========================================================================
# Workload 4: Stateful Database (Corrected)
#
# This version includes the 'subPath' fix to avoid the initdb error.
# =========================================================================

# --- Headless Service (unchanged, but needed for the StatefulSet) ---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: web
  clusterIP: None
  selector:
    app: postgres
---
# --- StatefulSet (Corrected) ---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
spec:
  serviceName: "postgres-headless"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:15.3-alpine
        ports:
        - containerPort: 5432
          name: postgres-db
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword" # Use secrets in a real environment
        - name: POSTGRES_DB
          value: "testdb"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          # --- THE FIX ---
          # This 'subPath' tells Kubernetes to create a 'data' directory
          # inside the volume and mount that instead of the volume's root.
          # This avoids the 'lost+found' directory problem.
          subPath: data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
