---
# =========================================================================
# Alvo: O StatefulSet 'postgres-db'.
# =========================================================================
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: postgres-db-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       StatefulSet
    name:       postgres-db
  updatePolicy:
    updateMode: "Off" # Apenas recomenda.